### ISSUE TITLE
destek 

### ISSUE THREAD

**Issue by muhammedfurkan** [xis/tdk#1]
destek kaldırıldı mı ? çalışmıyor.

**Comment by xis** [comment]
pip'den kaldırmıştım bir ara, kullanılmıyor çok diye geri yüklememiştim üşengeçlikten 😄 source'den direk kullanabilirsin, ilk fırsatta tekrar pip'e yüklüyücem.

**Comment by xis** [comment]
Tekrar selam, uygulamayı pypi'ye yükledim,
`pip install tdk-search`
yazarak yükleyip kullanabilirsin. 👍

**Comment by muhammedfurkan** [comment]
> Tekrar selam, uygulamayı pypi'ye yükledim,
> `pip install tdk-search`
> yazarak yükleyip kullanabilirsin. 👍

Teşekkür ederim.
